//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public file_type()
        {
            this.files = new HashSet<file>();
        }
    
        public int file_type_id { get; set; }
        public string file_type_code { get; set; }
        public string file_classification_code { get; set; }
        public bool active { get; set; }
        public string description { get; set; }
        public Nullable<int> min_number { get; set; }
        public Nullable<int> max_number { get; set; }
        public bool auto_generated { get; set; }
        public Nullable<int> current_number { get; set; }
        public string number_format { get; set; }
        public int min_size { get; set; }
        public Nullable<int> certificate_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        public virtual lkp_file_classification lkp_file_classification { get; set; }
    }
}
