//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ftms_transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ftms_transaction()
        {
            this.ftms_file = new HashSet<ftms_file>();
        }
    
        public int transaction_id { get; set; }
        public int file_id { get; set; }
        public string from_location { get; set; }
        public string to_location { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string file_condition { get; set; }
        public int number_page { get; set; }
        public string logged_user { get; set; }
        public string pc_name { get; set; }
        public string tracking_remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ftms_file> ftms_file { get; set; }
        public virtual ftms_file ftms_file1 { get; set; }
        public virtual ftms_locations ftms_locations { get; set; }
        public virtual ftms_locations ftms_locations1 { get; set; }
        public virtual lkp_file_condition lkp_file_condition { get; set; }
    }
}
