//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ftms_census
    {
        public int census_id { get; set; }
        public System.DateTime census_date { get; set; }
        public string location_code { get; set; }
        public int file_id { get; set; }
        public string logged_user { get; set; }
        public string pc_name { get; set; }
    
        public virtual ftms_file ftms_file { get; set; }
        public virtual ftms_locations ftms_locations { get; set; }
    }
}
