//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ftms_file_request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ftms_file_request()
        {
            this.request_details = new HashSet<request_details>();
        }
    
        public int request_id { get; set; }
        public string requestor_name { get; set; }
        public string request_purpose { get; set; }
        public System.DateTime request_date { get; set; }
        public string requestor_pcname { get; set; }
        public string requestor_logged_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_details> request_details { get; set; }
    }
}
