//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ftms_sticker
    {
        public int sticker_id { get; set; }
        public int file_id { get; set; }
        public string qr_full_text { get; set; }
        public System.DateTime created_date { get; set; }
        public string logged_user { get; set; }
        public bool active { get; set; }
    
        public virtual ftms_file ftms_file { get; set; }
    }
}
