//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ftmsdbEntities : DbContext
    {
        public ftmsdbEntities()
            : base("name=ftmsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ftms_census> ftms_census { get; set; }
        public virtual DbSet<ftms_file> ftms_file { get; set; }
        public virtual DbSet<ftms_file_request> ftms_file_request { get; set; }
        public virtual DbSet<ftms_locations> ftms_locations { get; set; }
        public virtual DbSet<ftms_setting> ftms_setting { get; set; }
        public virtual DbSet<ftms_sticker> ftms_sticker { get; set; }
        public virtual DbSet<ftms_transaction> ftms_transaction { get; set; }
        public virtual DbSet<lkp_file_condition> lkp_file_condition { get; set; }
        public virtual DbSet<request_details> request_details { get; set; }
        public virtual DbSet<allocation_status> allocation_status { get; set; }
        public virtual DbSet<appuser> appusers { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<file_status> file_status { get; set; }
        public virtual DbSet<file_type> file_type { get; set; }
        public virtual DbSet<lkp_file_classification> lkp_file_classification { get; set; }
        public virtual DbSet<lkp_state> lkp_state { get; set; }
        public virtual DbSet<location_type_upper> location_type_upper { get; set; }
        public virtual DbSet<logger> loggers { get; set; }
        public virtual DbSet<party> parties { get; set; }
        public virtual DbSet<setting> settings { get; set; }
    }
}
