//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ftms_file
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ftms_file()
        {
            this.ftms_census = new HashSet<ftms_census>();
            this.ftms_sticker = new HashSet<ftms_sticker>();
            this.ftms_transaction1 = new HashSet<ftms_transaction>();
            this.request_details = new HashSet<request_details>();
        }
    
        public int file_id { get; set; }
        public string file_number { get; set; }
        public string owner_name { get; set; }
        public bool cofo_exist { get; set; }
        public bool rofo_exist { get; set; }
        public string phone_number { get; set; }
        public Nullable<System.DateTime> app_date { get; set; }
        public string remark { get; set; }
        public string register_number { get; set; }
        public Nullable<System.DateTime> rofo_date { get; set; }
        public Nullable<System.DateTime> commencement_date { get; set; }
        public string file_alias { get; set; }
        public string lga_code { get; set; }
        public string rack_number { get; set; }
        public Nullable<int> current_transaction { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ftms_census> ftms_census { get; set; }
        public virtual ftms_transaction ftms_transaction { get; set; }
        public virtual location_type_upper location_type_upper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ftms_sticker> ftms_sticker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ftms_transaction> ftms_transaction1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_details> request_details { get; set; }
    }
}
