//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_details
    {
        public int request_id { get; set; }
        public int file_id { get; set; }
        public string note { get; set; }
    
        public virtual ftms_file ftms_file { get; set; }
        public virtual ftms_file_request ftms_file_request { get; set; }
    }
}
