using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FTMS.Common.DTOs
{
    public class FileType
    {
        public int fileTypeId { get; set; }        
        public string fileTypeCode { get; set; }        
        public Boolean active { get; set; }        
        public string description { get; set; }
        public int minNumber { get; set; }
        public int maxNumber { get; set; }                
        public Boolean autoGenerated { get; set; } 
        public int currentNumber { get; set; }
        public int certificateCode { get; set; }
        public string fileClassificationCode { get; set; }       
        public string numberFormat { get; set; }    
        public int minSize { get; set; }           
    }
}
